spring.application.name=F-Project
spring.config.import=optional:classpath:application-secrets.properties


spring.datasource.url=jdbc:mysql://localhost:3306/ala_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create-drop

spring.web.error.include-message=always
spring.jackson.serialization.indent-output=true

openai.model=gpt-4o-mini
wathq.base-url=https://api.wathq.sa

google.maps.geocoding.base-url=https://maps.googleapis.com/maps/api/geocode/json
google.maps.routes.base-url=https://routes.googleapis.com/directions/v2:computeRoutes

spring.profiles.active=local
google.sheets.base-url=https://sheets.googleapis.com/v4

spring.mail.username=moqr0505moqr@gmail.com
spring.mail.password=uavo rtfy bzhv uqki